// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Post: typeof import('./components/Post.vue')['default']
    PostSkeleton: typeof import('./components/PostSkeleton.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
